### PR TITLE
Several adjustments (late merge request :P)

### PR DESCRIPTION
**Pull request by ucyo**

### CODE REVIEW

**Comment by ucyo** [comment]
Sorry. Forgot about this ... :man_facepalming:

**Comment by bartromgens** [comment]
@trthhrtz @ucyo I cannot easily merge this because there are several difficult conflicts and several unwanted changes.

**Comment by bartromgens** [comment]
Ok, managed to merge! Thanks @ucyo

Will fix some minor things later and create a new release.

**Comment by techkuz** [comment]
thanks, @ucyo @bartromgens . Nice work, btw ;)

**Pull request merged**
